"""Regression tests for the capstone course documentation contract."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).parents[3]
SCRIPT = ROOT / "scripts" / "validate-course-docs.py"


def _load_validator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("validate_course_docs", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.mark.unit
def test_catalog_parser_preserves_lists_and_empty_not_implemented_fields(tmp_path: Path) -> None:
    module = _load_validator()
    fragment = tmp_path / "fragment.yaml"
    fragment.write_text(
        """- id: typed-runtime
  title: Typed runtime
  status: implemented
  module: docs/course/modules/02-typed-runtime/README.md
  sources:
    - backend/app/runtime/engine.py
  tests:
    - backend/tests/unit/test_runtime_v2.py
  evidence:
    - docs/IMPLEMENTATION-EVIDENCE.md
  limitations: Local evidence only.

- id: generic-self-reflection
  title: Generic self-reflection
  status: not-implemented
  module: docs/course/modules/03-react-loop/README.md
  sources: []
  tests: []
  evidence:
    - docs/IMPLEMENTATION-EVIDENCE.md
  limitations: ReAct and verification are different mechanisms.
""",
        encoding="utf-8",
    )

    entries = module.parse_catalog_fragment(fragment)

    assert [entry.identifier for entry in entries] == [
        "typed-runtime",
        "generic-self-reflection",
    ]
    assert entries[0].fields["sources"] == ["backend/app/runtime/engine.py"]
    assert entries[1].fields["sources"] == []
    assert entries[1].fields["status"] == "not-implemented"
    rendered = module.render_catalog([fragment])
    assert rendered.startswith("# Generated by")
    assert rendered.endswith("\n")
    assert "- id: typed-runtime" in rendered


@pytest.mark.unit
def test_current_course_documentation_satisfies_contract() -> None:
    module = _load_validator()

    issues = module.validate_repository(ROOT)

    assert issues == [], "\n".join(issues)
