<script lang="ts">
  import SourceLinks from './SourceLinks.svelte';
  import type { SourceReference } from '$lib/source-links';
  type Card = { id: string; question: string; answer: string; explanation: string; misconception: string; sources: SourceReference[] };
  let { cards, sourceCommit }: { cards: Card[]; sourceCommit: string } = $props();
  let index = $state(0); let revealed = $state(false); let ratings = $state<Record<string,string>>({});
  let card = $derived(cards[index]);
  function move(delta:number){index=Math.max(0,Math.min(cards.length-1,index+delta));revealed=false}
  function key(event:KeyboardEvent){if(event.key==='ArrowRight')move(1);if(event.key==='ArrowLeft')move(-1)}
</script>
<section class="cards" aria-label="Flashcard practice"><header><span>Practice progress — not completion evidence</span><strong>{index+1} / {cards.length}</strong></header><button class="card" onclick={()=>revealed=!revealed} onkeydown={key} aria-label={revealed?'Show question':'Reveal answer'}><span class="eyebrow">{revealed?'Answer':'Question'}</span><h3>{revealed?card.answer:card.question}</h3>{#if revealed}<p>{card.explanation}</p><div class="misconception"><strong>Common misconception</strong>{card.misconception}</div>{/if}</button><div class="nav"><button onclick={()=>move(-1)} disabled={index===0}>← Previous</button><fieldset><legend>Rate difficulty</legend>{#each ['easy','medium','hard'] as rating}<button aria-pressed={ratings[card.id]===rating} onclick={()=>ratings={...ratings,[card.id]:rating}}>{rating}</button>{/each}</fieldset><button onclick={()=>move(1)} disabled={index===cards.length-1}>Next →</button></div>{#if revealed}<SourceLinks sources={card.sources} {sourceCommit} compact />{/if}</section>
<style>.cards>header{display:flex;justify-content:space-between;color:var(--muted);font-size:.75rem;margin-bottom:.75rem}.card{width:100%;min-height:360px;border:1px solid var(--accent);border-radius:1rem;background:radial-gradient(circle at top,var(--cogentrex-orange-glow),transparent 50%),var(--panel);box-shadow:0 0 22px var(--cogentrex-orange-glow);color:var(--text);padding:clamp(1.5rem,5vw,4rem);text-align:center}.card h3{font-size:clamp(1.4rem,3vw,2.4rem);margin:1rem auto;max-width:28ch}.card p{color:var(--secondary);line-height:1.6}.misconception{margin:1rem auto 0;max-width:60ch;padding:1rem;border:1px solid rgba(240,189,98,.4);border-radius:.7rem;color:var(--warning);font-size:.85rem}.misconception strong{display:block;margin-bottom:.4rem}.nav{display:flex;justify-content:space-between;align-items:center;gap:.75rem;margin-top:1rem}.nav button{min-height:40px;border:1px solid var(--border);border-radius:.55rem;background:var(--bg);color:var(--text);padding:.5rem}.nav fieldset{border:0;display:flex;gap:.3rem}.nav legend{font-size:.65rem;color:var(--muted)}.nav button[aria-pressed="true"]{border-color:var(--accent);color:var(--accent);box-shadow:0 0 14px var(--cogentrex-orange-glow)}@media(max-width:650px){.nav{flex-wrap:wrap}.nav fieldset{order:3;width:100%;justify-content:center}}</style>
