<script lang="ts">
  import SourceLinks from './SourceLinks.svelte';
  import type { SourceReference } from '$lib/source-links';
  type Question = { id:string; scenario:string; options:string[]; correct_index:number; explanation:string; sources:SourceReference[] };
  let { questions, sourceCommit }: { questions: Question[]; sourceCommit: string } = $props();
  let index=$state(0);let selected=$state<number|null>(null);let answered=$state(false);let score=$state(0);
  let question=$derived(questions[index]);
  function submit(){if(selected===null||answered)return;answered=true;if(selected===question.correct_index)score+=1}
  function next(){if(index<questions.length-1){index+=1;selected=null;answered=false}}
  function reset(){index=0;selected=null;answered=false;score=0}
</script>
<section class="quiz" aria-label="Scenario quiz"><header><span>Question {index+1} of {questions.length}</span><strong>Score {score}</strong></header><article><h3>{question.scenario}</h3><fieldset disabled={answered}><legend>Select the best answer</legend>{#each question.options as option, optionIndex}<label class:chosen={selected===optionIndex}><input type="radio" name={question.id} value={optionIndex} checked={selected===optionIndex} onchange={()=>selected=optionIndex}/><span>{option}</span></label>{/each}</fieldset>{#if answered}<div role="alert" class:correct={selected===question.correct_index} class="feedback"><strong>{selected===question.correct_index?'Correct':'Not quite'}</strong><p>{question.explanation}</p></div><SourceLinks sources={question.sources} {sourceCommit} compact />{/if}</article><footer><button onclick={submit} disabled={selected===null||answered}>Check answer</button>{#if answered&&index<questions.length-1}<button onclick={next}>Next question →</button>{:else if answered}<button onclick={reset}>Try again</button>{/if}</footer></section>
<style>.quiz{border:1px solid var(--border);border-radius:1rem;background:var(--panel);padding:1rem}.quiz header{display:flex;justify-content:space-between;color:var(--muted);font-size:.75rem}.quiz h3{font-size:clamp(1.2rem,2.5vw,1.8rem);line-height:1.35}.quiz fieldset{border:0;padding:0;display:grid;gap:.65rem}.quiz legend{color:var(--muted);font-size:.75rem;margin-bottom:.6rem}.quiz label{display:flex;gap:.7rem;align-items:flex-start;border:1px solid var(--border);border-radius:.7rem;padding:.8rem;cursor:pointer}.quiz label.chosen{border-color:var(--accent);box-shadow:0 0 14px var(--archon-orange-glow)}.feedback{margin-top:1rem;border-left:3px solid var(--danger);padding:.8rem;background:rgba(255,107,114,.07)}.feedback.correct{border-color:var(--archon-green);background:color-mix(in srgb,var(--archon-green) 7%,transparent)}.feedback p{color:var(--secondary)}.quiz footer{display:flex;gap:.5rem;margin-top:1rem}.quiz button{min-height:42px;border:1px solid var(--accent);border-radius:.6rem;background:var(--accent-glow);color:var(--text);padding:.6rem 1rem}</style>
