import { expect, test, type Page } from '@playwright/test';
const instruction={id:'i1',relative_path:'AGENTS.md',scope_path:'.',revision:'4',content_hash:'abcdef1234567890',trust_state:'trusted',byte_count:240};
const skills=[{id:'skill-installed',revision_id:'rev-installed',name:'Code review',description:'Review changes safely',kind:'skill',source:'archon',version:'2.1.0',trust_state:'approved',enabled:true,pinned:false,risk_classes:['read']},{id:'skill-available',revision_id:'rev-available',name:'Release helper',description:'Prepare release notes',kind:'skill',source:'catalog',version:'1.0.0',trust_state:'pending',enabled:false,pinned:false,risk_classes:['write']}];
const capability={id:'tool-search',name:'search_docs',description:'Search approved documentation',kind:'mcp_tool',source:'official-docs',version:'1',trust_state:'verified',enabled:true,pinned:false,risk_classes:['network','read']};
async function mockSettings(page:Page){await page.addInitScript(()=>localStorage.setItem('archon_token','test-token'));await page.route('**/api/projects/default/instructions',r=>r.fulfill({contentType:'application/json',body:JSON.stringify([instruction])}));await page.route('**/api/skills/catalog?**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(skills)}));await page.route('**/api/capabilities/projects/default/effective',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({items:[capability]})}));await page.route('**/api/skills/projects/default/skill-installed',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({...skills[0],enabled:false})}));await page.route('**/api/mcp/profiles',r=>r.fulfill({contentType:'application/json',body:'[]'}));await page.route('**/api/mcp/servers?**',r=>r.fulfill({contentType:'application/json',body:'[]'}));}
test('desktop settings exposes scoped controls and backend-aligned mutations',async({page})=>{await mockSettings(page);await page.setViewportSize({width:1440,height:900});await page.goto('/settings');await expect(page.getByRole('heading',{name:'Settings'})).toBeVisible();await expect(page.getByRole('textbox', { name: /Project scope/ })).toHaveValue('default');await expect(page.getByText('AGENTS.md')).toBeVisible();await page.getByRole('tab',{name:'enabled'}).click();await page.getByRole('button',{name:'Disable Code review'}).click();await expect(page.getByRole('heading',{name:'MCP integrations'})).toBeVisible();await page.getByText('search_docs').click();await expect(page.getByText('verified')).toBeVisible();await expect(page.getByText(/top K/i)).toHaveCount(0);await expect(page.getByText(/Import from GitHub/i)).toHaveCount(0)});
test('mobile settings has 44px controls and no horizontal overflow',async({page})=>{await mockSettings(page);await page.setViewportSize({width:390,height:844});await page.goto('/settings');await expect(page.getByRole('heading',{name:'Workspace & Instructions'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);const boxes=await page.locator('button').evaluateAll(nodes=>nodes.slice(0,8).map(n=>n.getBoundingClientRect().height));expect(boxes.every(height=>height>=44)).toBe(true)});

test('run ledger loads effective context revisions hashes reasons and cost',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('archon_token','test-token'));
 const run={run_id:'run-ctx',conversation_id:'conversation-ctx',project_id:'default',provider:'test',model:'model',status:'completed',started_at:'2026-09-01T00:00:00Z',completed_at:'2026-09-01T00:00:01Z',answer_summary:'done',input_tokens:40,output_tokens:10,total_tokens:50,cost_usd:0.01,latency_ms:100,iterations:1,stop_reason:'complete',parent_run_id:null,fork_source_sequence:null};
 await page.route('**/healthz',r=>r.fulfill({contentType:'application/json',body:'{}'}));
 await page.route('**/api/admin/health',r=>r.fulfill({contentType:'application/json',body:'{}'}));
 await page.route('**/api/conversations',r=>r.fulfill({contentType:'application/json',body:'[]'}));
 await page.route('**/api/chat/history/conversation-ctx',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({messages:[]})}));
 await page.route('**/api/logs/stream',r=>r.fulfill({contentType:'text/event-stream',body:''}));
 await page.route('**/api/runs?**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({items:[run]})}));
 await page.route('**/api/runs/run-ctx/events?**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({items:[]})}));
 await page.route('**/api/runs/run-ctx/exports',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({items:[]})}));
 await page.route('**/api/runs/run-ctx',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(run)}));
 await page.route('**/api/runs/run-ctx/effective-context',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({run_id:'run-ctx',project_id:'default',manifest_hash:'manifesthash',instruction_revisions:[{id:'i1',source_path:'packages/app/AGENTS.md',resolution_order:2,revision:'4',content_hash:'abcdef1234567890',selection_reason:'active workspace scope',estimated_tokens:24}],skill_revisions:[{id:'s1',name:'Code review',revision_id:'skill-rev-2',content_hash:'skillhash123',selection_reason:'pinned by project'}],capabilities:[{id:'c1',name:'search_docs',schema_hash:'schema123456789',permission:'ask',reason:'matched request',estimated_tokens:12}],context_cost:{estimated_tokens:36,byte_count:420},omission_reasons:[]})}));
 await page.setViewportSize({width:1440,height:900});await page.goto('/chat/conversation-ctx');await page.getByText('Effective context',{exact:true}).click();const panel=page.getByTestId('effective-context').first();await expect(panel.getByText(/#2.*packages\/app\/AGENTS.md/)).toBeVisible();await expect(panel).toContainText('abcdef1234567890');await expect(panel.getByText('active workspace scope')).toBeVisible();await expect(panel.getByText('36')).toBeVisible();await expect(panel).toContainText('policy ask');await expect(panel).toContainText('Hidden reasoning and secret values are never shown');
});
