#!/usr/bin/env bash
set -Eeuo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
STATE_DIR=${XDG_STATE_HOME:-$HOME/.local/state}/cogentrex
STATE_FILE=${COGENTREX_RUNTIME_STATE_FILE:-$STATE_DIR/local-runtime.env}
LOCK_FILE="$STATE_DIR/start.lock"

usage() {
  cat <<'EOF'
Usage: ./scripts/local-stack.sh <command> [args]

Commands:
  start [--live-provider]  Build, verify, and retain the stack (mock by default)
  status                    Show current project state and verify /healthz and /readyz
  url                   Print the loopback application URL
  logs [SERVICE ...]    Read logs using retained context (label fallback if env is missing)
  stop                  Explicitly remove the managed project, volumes, env, and state

Do not invoke docker compose directly with backend/.env or dummy secrets.
EOF
}

load_state_metadata() {
  if [[ ! -f "$STATE_FILE" ]]; then
    printf 'No managed Cogentrex stack state at %s. Run: ./scripts/local-stack.sh start\n' "$STATE_FILE" >&2
    return 1
  fi
  # Generated by local-deploy-smoke.sh with mode 0600; contains paths/URL, not secret values.
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  : "${COGENTREX_COMPOSE_PROJECT:?missing project in state file}"
  : "${COGENTREX_COMPOSE_ENV_FILE:?missing env path in state file}"
  : "${COGENTREX_COMPOSE_FILE:?missing compose path in state file}"
  : "${COGENTREX_BASE_URL:?missing base URL in state file}"
  COGENTREX_RUNTIME_MODE=${COGENTREX_RUNTIME_MODE:-mock}
  COGENTREX_LLM_PROVIDER_NAME=${COGENTREX_LLM_PROVIDER_NAME:-mock}
  COGENTREX_LLM_MODEL_NAME=${COGENTREX_LLM_MODEL_NAME:-mock-model}
  COGENTREX_OTEL_COLLECTOR_CONFIG_FILE=${COGENTREX_OTEL_COLLECTOR_CONFIG_FILE:-}
  case "$COGENTREX_COMPOSE_PROJECT" in
    cogentrex-local-*) ;;
    *)
      printf 'Refusing unexpected Compose project in state: %s\n' "$COGENTREX_COMPOSE_PROJECT" >&2
      return 1
      ;;
  esac
  chmod 600 "$STATE_FILE"
}

prepare_compose_context() {
  load_state_metadata
  if [[ ! -f "$COGENTREX_COMPOSE_ENV_FILE" ]]; then
    printf 'Protected Compose env file is missing: %s\n' "$COGENTREX_COMPOSE_ENV_FILE" >&2
    return 1
  fi
  chmod 600 "$COGENTREX_COMPOSE_ENV_FILE"
  compose=(
    docker compose
    --env-file "$COGENTREX_COMPOSE_ENV_FILE"
    -f "$COGENTREX_COMPOSE_FILE"
    -p "$COGENTREX_COMPOSE_PROJECT"
  )
}

project_container_ids() {
  docker ps -aq --filter "label=com.docker.compose.project=$COGENTREX_COMPOSE_PROJECT"
}

project_ps_without_env() {
  docker ps -a --filter "label=com.docker.compose.project=$COGENTREX_COMPOSE_PROJECT"
}

project_logs_without_env() {
  local service=${1:-}
  local ids
  if [[ -n "$service" ]]; then
    ids=$(docker ps -aq \
      --filter "label=com.docker.compose.project=$COGENTREX_COMPOSE_PROJECT" \
      --filter "label=com.docker.compose.service=$service")
  else
    ids=$(project_container_ids)
  fi
  if [[ -z "$ids" ]]; then
    printf 'No containers found for managed project %s.\n' "$COGENTREX_COMPOSE_PROJECT" >&2
    return 1
  fi
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    docker logs "$id"
  done <<<"$ids"
}

remove_containers() {
  local ids=$1
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    docker rm -f "$id"
  done <<<"$ids"
}

remove_volumes() {
  local ids=$1
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    docker volume rm "$id"
  done <<<"$ids"
}

remove_networks() {
  local ids=$1
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    docker network rm "$id"
  done <<<"$ids"
}

stop_without_env() {
  local containers volumes networks
  containers=$(project_container_ids)
  volumes=$(docker volume ls -q --filter "label=com.docker.compose.project=$COGENTREX_COMPOSE_PROJECT")
  networks=$(docker network ls -q --filter "label=com.docker.compose.project=$COGENTREX_COMPOSE_PROJECT")
  remove_containers "$containers"
  remove_volumes "$volumes"
  remove_networks "$networks"
  rm -f "$STATE_FILE"
}

stop_loaded_stack() {
  if ! "${compose[@]}" down --volumes --remove-orphans; then
    printf 'Failed to stop the managed stack; preserving env and state for retry.\n' >&2
    return 1
  fi
  rm -f "$COGENTREX_COMPOSE_ENV_FILE"
  if [[ -n "$COGENTREX_OTEL_COLLECTOR_CONFIG_FILE" ]]; then
    rm -f "$COGENTREX_OTEL_COLLECTOR_CONFIG_FILE"
  fi
  rm -f "$STATE_FILE"
}

acquire_start_lock() {
  [[ "${COGENTREX_START_LOCK_HELD:-0}" == "1" ]] && return 0
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR"
  if [[ -d "$LOCK_FILE" ]]; then
    printf 'Legacy lock directory detected at %s; verify no start is active, remove it once, and retry.\n' "$LOCK_FILE" >&2
    return 1
  fi
  : >"$LOCK_FILE"
  chmod 600 "$LOCK_FILE"

  if command -v lockf >/dev/null 2>&1; then
    exec lockf -t 0 "$LOCK_FILE" env COGENTREX_START_LOCK_HELD=1 "$0" start "$@"
  fi
  if command -v flock >/dev/null 2>&1; then
    exec flock -n "$LOCK_FILE" env COGENTREX_START_LOCK_HELD=1 "$0" start "$@"
  fi
  printf 'No supported advisory lock primitive found (requires lockf or flock).\n' >&2
  return 1
}

command=${1:-}
if [[ -z "$command" ]]; then
  usage
  exit 2
fi
shift

case "$command" in
  start)
    requested_mode=mock
    provider_env=""
    case "${1:-}" in
      "") ;;
      --live-provider)
        requested_mode=live-foundry
        provider_env=${COGENTREX_PROVIDER_ENV_FILE:-$ROOT/backend/.env}
        ;;
      *)
        printf 'Unknown start option: %s\n' "$1" >&2
        usage >&2
        exit 2
        ;;
    esac
    if [[ $# -gt 1 ]]; then
      printf 'start accepts at most one option: --live-provider\n' >&2
      exit 2
    fi
    acquire_start_lock "$@"
    if [[ -f "$STATE_FILE" ]]; then
      if ! prepare_compose_context; then
        printf 'Managed runtime state exists but cannot be used. Preserving it for recovery; do not start another stack.\n' >&2
        exit 1
      fi
      if [[ "$COGENTREX_RUNTIME_MODE" != "$requested_mode" ]]; then
        printf 'Managed stack mode is %s, requested %s. Stop explicitly before changing provider mode.\n' \
          "$COGENTREX_RUNTIME_MODE" "$requested_mode" >&2
        exit 1
      fi
      if curl --fail --silent --show-error "$COGENTREX_BASE_URL/healthz" >/dev/null 2>&1 \
        && curl --fail --silent --show-error "$COGENTREX_BASE_URL/readyz" >/dev/null 2>&1; then
        printf 'Cogentrex is already running, healthy, and ready.\n'
        printf 'COGENTREX_URL=%s\n' "$COGENTREX_BASE_URL"
        printf 'STATE_FILE=%s\n' "$STATE_FILE"
        printf 'RUNTIME_MODE=%s\nLLM_PROVIDER=%s\nLLM_MODEL=%s\n' \
          "$COGENTREX_RUNTIME_MODE" "$COGENTREX_LLM_PROVIDER_NAME" "$COGENTREX_LLM_MODEL_NAME"
        exit 0
      fi
      printf 'Managed Cogentrex stack exists but health or readiness is failing. Preserving containers, volumes, env, and state.\n' >&2
      printf 'Inspect with: ./scripts/local-stack.sh status or logs; stop explicitly before a new start.\n' >&2
      "${compose[@]}" ps >&2 || true
      exit 1
    fi
    if [[ "$requested_mode" == "live-foundry" && ! -f "$provider_env" ]]; then
      printf 'Foundry provider env is missing: %s\n' "$provider_env" >&2
      exit 1
    fi
    COGENTREX_PROVIDER_ENV_FILE="$provider_env" KEEP=1 COGENTREX_RUNTIME_STATE_FILE="$STATE_FILE" \
      "$ROOT/scripts/local-deploy-smoke.sh"
    ;;
  status)
    load_state_metadata
    if [[ -f "$COGENTREX_COMPOSE_ENV_FILE" ]]; then
      prepare_compose_context
      "${compose[@]}" ps
      curl --fail --silent --show-error "$COGENTREX_BASE_URL/healthz" >/dev/null
      curl --fail --silent --show-error "$COGENTREX_BASE_URL/readyz" >/dev/null
      printf 'STATUS=ready\n'
      printf 'COGENTREX_URL=%s\n' "$COGENTREX_BASE_URL"
      printf 'RUNTIME_MODE=%s\nLLM_PROVIDER=%s\nLLM_MODEL=%s\n' \
        "$COGENTREX_RUNTIME_MODE" "$COGENTREX_LLM_PROVIDER_NAME" "$COGENTREX_LLM_MODEL_NAME"
    else
      printf 'STATUS=unmanaged-missing-env\n' >&2
      project_ps_without_env
      printf 'Protected env is missing; use logs for diagnosis or stop for explicit label-scoped cleanup.\n' >&2
      exit 1
    fi
    ;;
  url)
    load_state_metadata
    printf '%s\n' "$COGENTREX_BASE_URL"
    ;;
  logs)
    load_state_metadata
    if [[ -f "$COGENTREX_COMPOSE_ENV_FILE" ]]; then
      prepare_compose_context
      "${compose[@]}" logs "$@"
    else
      printf 'Protected env is missing; reading logs through exact Compose project labels.\n' >&2
      project_logs_without_env "${1:-}"
    fi
    ;;
  stop)
    load_state_metadata
    if [[ -f "$COGENTREX_COMPOSE_ENV_FILE" ]]; then
      prepare_compose_context
      stop_loaded_stack
    else
      printf 'Protected env is missing; removing only resources labeled for project %s.\n' "$COGENTREX_COMPOSE_PROJECT" >&2
      stop_without_env
    fi
    printf 'Cogentrex local stack stopped; volumes, protected env (when present), and state removed.\n'
    ;;
  -h | --help | help)
    usage
    ;;
  *)
    printf 'Unknown command: %s\n' "$command" >&2
    usage >&2
    exit 2
    ;;
esac
