#!/usr/bin/env python3
"""Validate Archon's course documentation contracts with the Python standard library."""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

ALLOWED_STATUSES = {"implemented", "partial", "not-implemented", "deferred"}
MODULE_SLUGS = [
    "00-agent-anatomy",
    "01-python-architecture",
    "02-typed-runtime",
    "03-react-loop",
    "04-tools-and-schemas",
    "05-policy-and-approvals",
    "06-context-and-memory",
    "07-run-ledger",
    "08-rag-grounding",
    "09-evaluation-harness",
    "10-resilience",
    "11-bounded-delegation",
    "12-governed-mcp",
    "13-auth-ui-observability",
    "14-local-operations",
    "15-capstone",
]
LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
ENTRY_RE = re.compile(r"^- id:\s*(\S+)\s*$")
FIELD_RE = re.compile(r"^  ([a-z_]+):\s*(.*)\s*$")
LIST_ITEM_RE = re.compile(r"^    -\s*(.+?)\s*$")
QUESTION_RE = re.compile(r"^\s*\d+[.)]\s+", re.MULTILINE)
CATALOG_HEADER = "# Generated by scripts/validate-course-docs.py --write-catalog. Do not edit.\n\n"


@dataclass(frozen=True)
class CatalogEntry:
    source_file: Path
    identifier: str
    fields: dict[str, str | list[str]]


def _headings(text: str) -> list[str]:
    return [line[3:].strip().lower() for line in text.splitlines() if line.startswith("## ")]


def _section(text: str, heading_contains: str) -> str:
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if line.startswith("## ") and heading_contains in line.lower():
            start = index + 1
            break
    if start is None:
        return ""
    end = len(lines)
    for index in range(start, len(lines)):
        if lines[index].startswith("## "):
            end = index
            break
    return "\n".join(lines[start:end])


def _has_heading(headings: Iterable[str], *terms: str) -> bool:
    return any(any(term in heading for term in terms) for heading in headings)


def parse_catalog_fragment(path: Path) -> list[CatalogEntry]:
    """Parse the deliberately small YAML subset used by catalog fragments."""
    entries: list[CatalogEntry] = []
    current_id: str | None = None
    current: dict[str, str | list[str]] = {}
    active_list: str | None = None

    def finish() -> None:
        nonlocal current_id, current, active_list
        if current_id is not None:
            entries.append(CatalogEntry(path, current_id, dict(current)))
        current_id = None
        current = {}
        active_list = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        match = ENTRY_RE.match(raw)
        if match:
            finish()
            current_id = match.group(1)
            continue
        field_match = FIELD_RE.match(raw)
        if field_match and current_id is not None:
            key, value = field_match.groups()
            if value == "[]":
                current[key] = []
                active_list = None
            elif value:
                current[key] = value.strip("\"'")
                active_list = None
            else:
                current[key] = []
                active_list = key
            continue
        item_match = LIST_ITEM_RE.match(raw)
        if item_match and current_id is not None and active_list:
            value = item_match.group(1).strip("\"'")
            target = current.setdefault(active_list, [])
            if isinstance(target, list):
                target.append(value)
            continue
        raise ValueError(f"unsupported catalog syntax at {path}:{raw!r}")
    finish()
    return entries


def _validate_module(path: Path, issues: list[str]) -> None:
    if not path.exists():
        issues.append(f"missing module: {path}")
        return
    text = path.read_text(encoding="utf-8")
    headings = _headings(text)
    required_groups = [
        ("outcome", "prerequisite"),
        ("mental model", "problem"),
        ("source", "code"),
        ("test", "evidence"),
        ("exercise", "probe", "drill", "try it"),
        ("security", "failure"),
        ("observability", "evidence path"),
        ("lab", "production"),
        ("interview",),
        ("self-check",),
        ("done",),
    ]
    for group in required_groups:
        if not _has_heading(headings, *group):
            issues.append(f"{path}: missing heading matching {group}")
    if len(text.splitlines()) < 65:
        issues.append(f"{path}: fewer than 65 lines; module is too shallow")
    if text.count("```mermaid") < 2:
        issues.append(f"{path}: fewer than two Mermaid diagrams")
    if text.count("```") % 2:
        issues.append(f"{path}: unbalanced fenced code block")
    self_check = _section(text, "self-check")
    if len(QUESTION_RE.findall(self_check)) < 5:
        issues.append(f"{path}: self-check has fewer than five numbered questions")


def _validate_concept(path: Path, issues: list[str]) -> None:
    text = path.read_text(encoding="utf-8")
    lowered = text.lower()
    if len(text.splitlines()) < 70:
        issues.append(f"{path}: fewer than 70 lines; concept is too shallow")
    if "```mermaid" not in text:
        issues.append(f"{path}: missing concept-specific Mermaid diagram")
    required_groups = [
        ("source", "implementation", "code"),
        ("test",),
        ("interview", "30-second answer"),
        ("self-check",),
    ]
    for group in required_groups:
        if not any(term in lowered for term in group):
            issues.append(f"{path}: missing required concept section matching {group}")
    if len(QUESTION_RE.findall(_section(text, "self-check"))) < 5:
        issues.append(f"{path}: self-check has fewer than five numbered questions")


def _validate_markdown_links(course_root: Path, issues: list[str]) -> None:
    for path in sorted(course_root.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        if text.count("```") % 2:
            issues.append(f"{path}: unbalanced fenced code block")
        if path.parent.name == "templates":
            continue
        for placeholder in ("<relative-link>", "<source-link>", "<test-link>"):
            if placeholder in text:
                issues.append(f"{path}: unresolved template placeholder {placeholder}")
        for target in LINK_RE.findall(text):
            target = target.strip().split("#", 1)[0]
            if not target or target.startswith(("http://", "https://", "mailto:")):
                continue
            resolved = (path.parent / target).resolve()
            if not resolved.exists():
                issues.append(f"{path}: broken link {target}")


def render_catalog(fragments: list[Path]) -> str:
    body = "\n".join(fragment.read_text(encoding="utf-8").strip() for fragment in fragments)
    return CATALOG_HEADER + body + "\n"


def _validate_catalog(repo_root: Path, course_root: Path, issues: list[str]) -> None:
    fragments = sorted((course_root / "catalog-fragments").glob("[0-9][0-9]-*.yaml"))
    if len(fragments) < 3:
        issues.append("expected at least three catalog fragments")
        return
    catalog = course_root / "concept-catalog.yaml"
    expected_catalog = render_catalog(fragments)
    if not catalog.exists():
        issues.append("missing generated concept-catalog.yaml")
    elif catalog.read_text(encoding="utf-8") != expected_catalog:
        issues.append("concept-catalog.yaml is stale; run validator with --write-catalog")
    entries: list[CatalogEntry] = []
    for fragment in fragments:
        try:
            entries.extend(parse_catalog_fragment(fragment))
        except ValueError as exc:
            issues.append(str(exc))
    seen: set[str] = set()
    for entry in entries:
        prefix = f"{entry.source_file}:{entry.identifier}"
        if entry.identifier in seen:
            issues.append(f"duplicate catalog id: {entry.identifier}")
        seen.add(entry.identifier)
        status = entry.fields.get("status")
        if status not in ALLOWED_STATUSES:
            issues.append(f"{prefix}: invalid status {status!r}")
        module = entry.fields.get("module")
        if not isinstance(module, str) or not (repo_root / module).exists():
            issues.append(f"{prefix}: missing module path {module!r}")
        for field in ("sources", "tests", "evidence"):
            values = entry.fields.get(field, [])
            if not isinstance(values, list):
                issues.append(f"{prefix}: {field} must be a list")
                continue
            if status == "implemented" and not values:
                issues.append(f"{prefix}: implemented concept requires {field}")
            for value in values:
                clean = value.split("#", 1)[0]
                if clean.startswith(("http://", "https://")):
                    continue
                if not (repo_root / clean).exists():
                    issues.append(f"{prefix}: missing {field} path {value}")
        limitation = entry.fields.get("limitations")
        if not isinstance(limitation, str) or not limitation.strip():
            issues.append(f"{prefix}: limitations are required")
    reflection_is_honest = any(
        entry.identifier == "generic-self-reflection"
        and entry.fields.get("status") == "not-implemented"
        for entry in entries
    )
    if not reflection_is_honest:
        issues.append("catalog must mark generic-self-reflection as not-implemented")


def validate_repository(repo_root: Path) -> list[str]:
    repo_root = repo_root.resolve()
    course_root = repo_root / "docs" / "course"
    issues: list[str] = []
    for required in ("README.md", "syllabus.md", "concept-map.md"):
        if not (course_root / required).exists():
            issues.append(f"missing course root file: {required}")
    for slug in MODULE_SLUGS:
        _validate_module(course_root / "modules" / slug / "README.md", issues)
    for concept in sorted((course_root / "concepts").glob("*.md")):
        _validate_concept(concept, issues)
    _validate_markdown_links(course_root, issues)
    _validate_catalog(repo_root, course_root, issues)
    return sorted(set(issues))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write-catalog", action="store_true")
    args = parser.parse_args()
    if args.write_catalog:
        course_root = args.root.resolve() / "docs" / "course"
        fragments = sorted((course_root / "catalog-fragments").glob("[0-9][0-9]-*.yaml"))
        if len(fragments) < 3:
            print("Cannot write catalog: expected at least three fragments")
            return 1
        (course_root / "concept-catalog.yaml").write_text(
            render_catalog(fragments), encoding="utf-8"
        )
    issues = validate_repository(args.root)
    if issues:
        print(f"Course documentation validation failed with {len(issues)} issue(s):")
        for issue in issues:
            print(f"- {issue}")
        return 1
    print("Course documentation validation passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
