<script lang="ts">
 import { Activity, Pin, PowerOff, Wrench } from 'lucide-svelte';
 import { disableCapability, listEffectiveCapabilities, pinCapability, type Capability } from '$lib/capabilities';
 let { projectId }: { projectId: string } = $props();
 let items: Capability[]=$state([]); let loading=$state(true); let error=$state(''); let busy=$state('');
 async function load(){loading=true;error='';try{items=await listEffectiveCapabilities(projectId)}catch(e){error=e instanceof Error?e.message:'Capability inventory unavailable'}finally{loading=false}}
 async function pin(item:Capability){busy=item.id;try{const next=await pinCapability(projectId,item.id);items=items.map(x=>x.id===item.id?{...x,...next,pinned:true}:x)}catch(e){error=e instanceof Error?e.message:'Pin failed'}finally{busy=''}}
 async function disable(item:Capability){busy=item.id;try{const next=await disableCapability(projectId,item.id);items=items.map(x=>x.id===item.id?{...x,...next,selected:false,executable:false}:x)}catch(e){error=e instanceof Error?e.message:'Disable failed'}finally{busy=''}}
 $effect(()=>{projectId;queueMicrotask(()=>void load())});
 const permissionTone=(p:string)=>p==='allow'?'text-[var(--accent)]':p==='ask'?'text-[var(--warning)]':'text-[var(--danger)]';
</script>
<section id="capabilities" aria-labelledby="capabilities-title" class="rounded-xl border border-[var(--border)] bg-[var(--panel)] p-4 sm:p-5">
 <div><p class="eyebrow">Runtime exposure</p><h2 id="capabilities-title" class="mt-1 text-base font-semibold">Tools &amp; MCP capability inventory</h2><p class="mt-1 text-xs leading-5 text-[var(--muted)]">Inventory and policy state only. Viewing or selecting a capability never executes it.</p></div>
 {#if loading}<div class="mt-4 p-5 text-sm text-[var(--muted)]" aria-live="polite">Loading capabilities…</div>{:else if error}<div class="mt-4 rounded-lg border border-[rgba(255,107,114,.4)] p-3 text-sm text-[var(--danger)]" role="alert">{error}<button class="ml-2 underline" onclick={load}>Retry</button></div>{:else if !items.length}<div class="mt-4 rounded-lg border border-dashed border-[var(--border)] p-6 text-center text-sm text-[var(--muted)]">No visible capabilities for this project.</div>{:else}<div class="mt-4 space-y-2">{#each items as item (item.id)}<details class="rounded-lg border border-[var(--border)] bg-[var(--panel-2)]"><summary class="flex min-h-11 cursor-pointer list-none items-center gap-3 px-3 py-2"><Wrench size={16} class="shrink-0 text-[var(--purple)]"/><span class="min-w-0 flex-1"><strong class="block truncate text-sm">{item.name}</strong><small class="text-[var(--muted)]">{item.kind.replace('_',' ')} · {item.source}</small></span><span class="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] {permissionTone(item.permission)}">{item.permission}</span></summary><div class="border-t border-[var(--border)] p-3"><p class="mt-0 text-xs leading-5 text-[var(--secondary)]">{item.description}</p><dl class="grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><div><dt class="text-[var(--muted)]">Visible</dt><dd>{item.visible?'Yes':'No'}</dd></div><div><dt class="text-[var(--muted)]">Selected</dt><dd>{item.selected?'Yes':'No'}</dd></div><div><dt class="text-[var(--muted)]">Executable</dt><dd>{item.executable?'Yes':'No'}</dd></div><div><dt class="text-[var(--muted)]">Version</dt><dd>{item.version}</dd></div>{#if item.transport}<div><dt class="text-[var(--muted)]">Transport</dt><dd>{item.transport}</dd></div>{/if}{#if item.health}<div><dt class="text-[var(--muted)]">Health</dt><dd class="flex items-center gap-1"><Activity size={12}/>{item.health}</dd></div>{/if}</dl><div class="mt-3 flex flex-wrap gap-1">{#each item.risk_classes as risk}<span class="rounded border border-[var(--border)] px-2 py-1 text-[10px] text-[var(--muted)]">{risk}</span>{/each}</div><div class="mt-3 flex justify-end gap-2"><button class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-xs disabled:opacity-50" disabled={busy===item.id||item.pinned} onclick={()=>pin(item)}><Pin size={14}/>{item.pinned?'Pinned':'Pin'}</button><button class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-xs text-[var(--danger)]" disabled={busy===item.id||!item.selected} onclick={()=>disable(item)}><PowerOff size={14}/>Disable</button></div></div></details>{/each}</div>{/if}
</section>
