<script lang="ts">
  import { Download, Pin, Package, ToggleLeft, ToggleRight } from 'lucide-svelte';
  import { enableSkill, listSkillCatalog, pinSkill, requestSkillInstall, type SkillCatalogItem } from '$lib/skills';
  let { projectId }: { projectId: string } = $props();
  let skills: SkillCatalogItem[] = $state([]); let active = $state<'installed'|'available'|'enabled'>('installed');
  let loading = $state(true); let error = $state(''); let busy = $state(''); let notice = $state('');
  const filtered = $derived(skills.filter((s) => active === 'enabled' ? s.enabled : active === 'available' ? !s.enabled : s.source !== 'catalog' || s.enabled));
  async function load() { loading=true; error=''; try { skills=await listSkillCatalog(); } catch(e){ error=e instanceof Error?e.message:'Skills unavailable'; } finally{loading=false;} }
  async function toggle(item: SkillCatalogItem){ busy=item.id; try { const next=await enableSkill(projectId,item.id,!item.enabled); skills=skills.map(s=>s.id===item.id?{...s,...next,enabled:!item.enabled}:s); } catch(e){error=e instanceof Error?e.message:'Update failed';} finally{busy='';} }
  async function pin(item: SkillCatalogItem){ busy=item.id; try { const next=await pinSkill(projectId,item.id); skills=skills.map(s=>s.id===item.id?{...s,...next,pinned:true}:s); } catch(e){error=e instanceof Error?e.message:'Pin failed';} finally{busy='';} }
  async function install(item: SkillCatalogItem){ busy=item.id; try { await requestSkillInstall(item.id); notice=`Install requested for ${item.name}. Review is required before enablement.`; } catch(e){error=e instanceof Error?e.message:'Install request failed';} finally{busy='';} }
  $effect(()=>{ projectId; queueMicrotask(()=>void load()); });
</script>
<section id="skills" aria-labelledby="skills-title" class="rounded-xl border border-[var(--border)] bg-[var(--panel)] p-4 sm:p-5">
 <div><p class="eyebrow">Governed packages</p><h2 id="skills-title" class="mt-1 text-base font-semibold">Skills Catalog</h2><p class="mt-1 text-xs leading-5 text-[var(--muted)]">Enable reviewed revisions for this project. External installs enter a review queue.</p></div>
 <div class="mt-4 grid grid-cols-3 rounded-lg border border-[var(--border)] p-1" role="tablist" aria-label="Skill catalog filters">{#each ['installed','available','enabled'] as tab}<button role="tab" aria-selected={active===tab} class="min-h-11 rounded-md px-2 text-xs capitalize {active===tab?'bg-[rgba(85,214,190,.12)] text-[var(--accent)]':'text-[var(--muted)]'}" onclick={()=>active=tab as typeof active}>{tab}</button>{/each}</div>
 {#if notice}<div class="mt-3 rounded-lg border border-[rgba(85,214,190,.3)] bg-[rgba(85,214,190,.08)] p-3 text-xs text-[var(--accent)]" role="status">{notice}</div>{/if}
 {#if error}<div class="mt-3 rounded-lg border border-[rgba(255,107,114,.4)] p-3 text-xs text-[var(--danger)]" role="alert">{error}<button class="ml-2 underline" onclick={load}>Retry</button></div>{/if}
 {#if loading}<div class="mt-4 p-5 text-sm text-[var(--muted)]" aria-live="polite">Loading catalog…</div>{:else if !filtered.length}<div class="mt-4 rounded-lg border border-dashed border-[var(--border)] p-6 text-center text-sm text-[var(--muted)]">No {active} skills.</div>{:else}<div class="mt-4 space-y-2">{#each filtered as item (item.id)}<article class="rounded-lg border border-[var(--border)] bg-[var(--panel-2)] p-3"><div class="flex items-start gap-3"><Package size={17} class="mt-1 shrink-0 text-[var(--purple)]"/><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h3 class="text-sm font-semibold">{item.name}</h3><span class="text-[10px] text-[var(--muted)]">v{item.version} · {item.source}</span>{#if item.pinned}<span class="rounded-full bg-[rgba(85,214,190,.1)] px-2 py-1 text-[10px] text-[var(--accent)]">Pinned</span>{/if}</div><p class="my-2 text-xs leading-5 text-[var(--secondary)]">{item.description}</p><div class="flex flex-wrap gap-1">{#each item.risk_classes as risk}<span class="rounded border border-[var(--border)] px-2 py-1 text-[10px] text-[var(--muted)]">{risk}</span>{/each}<span class="rounded border border-[var(--border)] px-2 py-1 text-[10px] text-[var(--muted)]">{item.trust_state}</span></div></div></div><div class="mt-3 flex flex-wrap justify-end gap-2">{#if active==='available'}<button class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-xs" disabled={busy===item.id} onclick={()=>install(item)}><Download size={14}/>Request install</button>{/if}<button aria-label={`Pin ${item.name}`} class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-xs disabled:opacity-50" disabled={busy===item.id || item.pinned} onclick={()=>pin(item)}><Pin size={14}/>Pin</button><button aria-label={`${item.enabled?'Disable':'Enable'} ${item.name}`} class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-xs" disabled={busy===item.id} onclick={()=>toggle(item)}>{#if item.enabled}<ToggleRight size={17} class="text-[var(--accent)]"/>Enabled{:else}<ToggleLeft size={17}/>Enable{/if}</button></div></article>{/each}</div>{/if}
</section>
