import { beforeEach, describe, expect, it, vi } from 'vitest';
vi.mock('$lib/auth', () => ({ authenticatedFetch: vi.fn() }));
import { authenticatedFetch } from '$lib/auth';
import { createProjectWorkspace, listProjectInstructions, scanProjectWorkspace } from './project-instructions';
import { bindSkill, listEffectiveSkills, listSkillCatalog, requestSkillInstall } from './skills';
import { disableCapability, listEffectiveCapabilities, pinCapability } from './capabilities';
const api=vi.mocked(authenticatedFetch);
const ok=(body:unknown,status=200)=>new Response(status===204?null:JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
beforeEach(()=>api.mockReset());
describe('project settings typed clients',()=>{
 it('matches project instruction routes, payloads and response shape',async()=>{api.mockResolvedValueOnce(ok([{id:'i1',relative_path:'AGENTS.md',scope_path:'.',revision:7,content_hash:'abc',trust_state:'trusted',byte_count:12}])).mockResolvedValueOnce(ok([])).mockResolvedValueOnce(ok({project_id:'team/a',status:'ready'},201));expect((await listProjectInstructions('team/a'))[0].revision).toBe(7);await scanProjectWorkspace('team/a','src');await createProjectWorkspace('team/a');expect(api.mock.calls.map(x=>[x[0],x[1]?.method])).toEqual([['/api/projects/team%2Fa/instructions',undefined],['/api/projects/team%2Fa/instructions/scan','POST'],['/api/projects/team%2Fa/workspace','POST']]);expect(JSON.parse(String(api.mock.calls[1][1]?.body))).toEqual({target_path:'src',family:'archon'})});
 it('matches catalog, effective, pinned install and binding contracts',async()=>{api.mockImplementation(async()=>ok([]));await listSkillCatalog('project/a');await listEffectiveSkills('project/a');await bindSkill('project/a','skill/1','rev-7','archon',true,true);await requestSkillInstall({repository:'https://example.test/repo.git',revision:'a'.repeat(40)});expect(api.mock.calls.map(x=>[x[0],x[1]?.method])).toEqual([['/api/skills/catalog?project_id=project%2Fa',undefined],['/api/skills/projects/project%2Fa/effective',undefined],['/api/skills/projects/project%2Fa/skill%2F1','PUT'],['/api/skills/install-requests','POST']]);expect(JSON.parse(String(api.mock.calls[2][1]?.body))).toEqual({revision_id:'rev-7',revision_owner_id:'archon',enabled:true,pinned:true});expect(JSON.parse(String(api.mock.calls[3][1]?.body))).toEqual({repository:'https://example.test/repo.git',revision:'a'.repeat(40),path:'SKILL.md'})});
 it('uses POST effective and PUT preference with complete capability payloads',async()=>{const item={id:'tool/x',name:'x',description:'x',kind:'native',source:'builtin',version:'1',trust_state:'verified',enabled:true,pinned:false,risk_classes:['read']};api.mockResolvedValueOnce(ok({items:[item]})).mockResolvedValueOnce(ok({...item,pinned:true})).mockResolvedValueOnce(ok({...item,enabled:false}));await listEffectiveCapabilities('p/a');await pinCapability('p/a',item);await disableCapability('p/a',item);expect(api.mock.calls.map(x=>[x[0],x[1]?.method])).toEqual([['/api/capabilities/projects/p%2Fa/effective','POST'],['/api/capabilities/projects/p%2Fa/tool%2Fx','PUT'],['/api/capabilities/projects/p%2Fa/tool%2Fx','PUT']]);expect(JSON.parse(String(api.mock.calls[0][1]?.body))).toEqual({});expect(JSON.parse(String(api.mock.calls[1][1]?.body))).toEqual({enabled:true,pinned:true});expect(JSON.parse(String(api.mock.calls[2][1]?.body))).toEqual({enabled:false,pinned:false})});
});
